### ISSUE TITLE
not correct CSV export

### ISSUE THREAD

**Issue by MalteKiefer** [lainsce/khronos#10]
Hi,

here must be an error:
https://github.com/lainsce/khronos/blob/f5686e92fe15c1f4ba77f6625607b9fde68dec84/src/Services/FileManager.vala#L46
export looks like this:

```
task,time,startdate
"Issues Ingo,"1 hrs, 3 mins, 26 secs","Started on: 2020-02-13 05:48
------------^
-------------------------------------------------------------------^
missing "
```

**Comment by lainsce** [comment]
Oh oops, must be something I typo'd. Sorry!

**Comment by lainsce** [comment]
Oh, that last comma you pointed out at the end is unnecessary, so only the first one missing was a bug.

**Comment by lainsce** [comment]
Fixed.
