### ISSUE TITLE
The button to stop the timer behaves unexpectedly

### ISSUE THREAD

**Issue by oscfdezdz** [lainsce/khronos#106]
Version 3.6.6

Hi, looking at my logs, I noticed start and end times of a task don't match the time it really takes. I usually stop the timer to take a break and resume it to continue. Start time seems to set to the last time start button is clicked and since the timer could have been running for a few more hours, the end time could end up being a few hours ahead the current time, is it the expected behavior?

Also, wouldn't a pause symbolic fit better in this case as the timer doesn't reset?

I can open a PR for this as I've tinkered with the code locally 😄 

**Edit:** my take would be to set start time to the moment start button is clicked for the first time and end time to the last time stop/pause button is clicked before adding to the log. This may cause the timer time to be less than the time that has elapsed between start and end, which is what I would expect.

**Comment by lainsce** [comment]
I see! Yeah, if you can change the code to do this since you have an idea of what to change, I'll oversee your PR. :)
