### ISSUE TITLE
About Khronos doesn't have a project link

### ISSUE THREAD

**Issue by RDKRACZ** [lainsce/khronos#108]
There should be a link to the issue tracker.

![image](https://user-images.githubusercontent.com/43277609/159898500-152afbe4-642c-4527-bcfd-117a01adc1b6.png)
![image](https://user-images.githubusercontent.com/43277609/159898534-28fea807-dc80-4b1c-9044-8b0f1723d86b.png)

**Comment by lainsce** [comment]
The link is in GNOME Software and other appdata-aware software management apps.

**Comment by RDKRACZ** [comment]
How is that linked to this issue? I don't have any software store and I don't need it. What I need is a quick way to find an issue tracker.
Why are your name and the license in the about dialog then? It's probably also present in the "appdata-aware software management apps"

**Comment by lainsce** [comment]
If you're gonna start to talk with that confrontational tone with me, I'm sorry but I won't cooperate with you. :/

If you don't have any appdata-aware software management apps, the GNOME about dialog here doesn't have a way to display the issue tracker URL. _That might change in the future._

If you don't need any appdata-aware software management apps, _that's on you for making that choice._
