### ISSUE TITLE
Reset not working

### ISSUE THREAD

**Issue by MalteKiefer** [lainsce/khronos#11]
When you run the counter more then an hour you can not reset it under an hour.
![khron](https://user-images.githubusercontent.com/59220985/74419951-f4cf6380-4e4a-11ea-870e-c68dd048a13b.gif)

**Comment by lainsce** [comment]
I'll look into it as soon as I can.

**Comment by lainsce** [comment]
What's happening here is that the hour timer isn't being resetted properly

**Comment by lainsce** [comment]
Fixed.

**Comment by MalteKiefer** [comment]
I think the best here is, when I tracked time is added to the list, the timer and the entry should be reset.

**Comment by lainsce** [comment]
I was on the fence about it because there's sort of a user flow between buttons in the recent release that I think makes sense?
