### ISSUE TITLE
AppCenter Description

### ISSUE THREAD

**Issue by MalteKiefer** [lainsce/khronos#12]
Some errors in the AppCenter Description.

![image](https://user-images.githubusercontent.com/59220985/74428564-91006700-4e59-11ea-88b4-2a97e316837c.png)

**Comment by lainsce** [comment]
Must be from those extra translation files in the `po/extra` folder... They are a headache that people edit wrong...

**Comment by MalteKiefer** [comment]
I will take a look.
The German translation is a mess.

**Comment by NathanBnm** [comment]
> Must be from those extra translation files in the `po/extra` folder... They are a headache that people edit wrong...

How is this related? I see the same issue with original strings in AppCenter. It looks like <ul></ul> and <li></li> tags are not supported in this AppCenter view.

**Comment by lainsce** [comment]
They were always supported...

**Comment by lainsce** [comment]
I found the problem, a new release of appcenter has made changes to the description text to strip things but I think they forgot to adequate for ULs. Not a bug on me.
