### ISSUE TITLE
[Feature Request] Upgrade to the new Adw.AboutWindow

### ISSUE THREAD

**Issue by Scotty-Trees** [lainsce/khronos#125]
As per https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/class.AboutWindow.html there is a new About Dialog Window for GTK4/libadwaita. Would love to see khronos using it at some point in the future too, thank you.

**Comment by lainsce** [comment]
As per the above PR being merged, Khronos now has this. Closing.
