### ISSUE TITLE
Follow HIG / GNOME Styling

### ISSUE THREAD

**Issue by iamcult** [lainsce/khronos#127]
While the new Solo UI is a nice looking UI, it does not look like a GNOME application, or properly follow GNOME HIG anymore (tabs, search, etc.). These inconsistencies make the app stick out like a sore thumb, and I'm also 90% sure could disqualify it for GNOME Circle. There are multiple other GTK4/Libadwaita time tracker apps available, and until now I considered this to be the best one, so it's sad for me that I might have to switch just for a consistent experience. 

It is true that it's your app, and I have no right to dictate what it looks like, but I thought maybe I could give some input from the perspective of a GNOME user who would like their desktop and apps to look consistent.

Sorry if this issue came across as heated, please don't take it the wrong way. It's well within your right to just close this if you disagree.

**Comment by aleksrutins** [comment]
It looks like this has happened in the latest master branch, but hasn't made it out to Flathub yet; see https://github.com/lainsce/khronos/commit/5983b1efa1d4a6d78c982e74cbc7d445d66aba51.

**Comment by lainsce** [comment]
Yup, this was already fixed because of Khronos being accepted as a GNOME Circle app. I just haven't got the time to do the flathub update yet. Busy with lots of things.
