### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by MalteKiefer** [lainsce/khronos#16]
Please do not sort by title but by starting time. I want to see at the top of the list what I have tracked last and don't need to search. Or a button that gives me the possibility to decide how I want to sort.

![image](https://user-images.githubusercontent.com/59220985/74503088-1a627880-4ef0-11ea-9db8-1eef28daf549.png)

**Comment by lainsce** [comment]
I'll be adding sort modes soon, it was a planned enhancement. :smile:

**Comment by lainsce** [comment]
Fixed!
