### ISSUE TITLE
Incorrect timer seconds

### ISSUE THREAD

**Issue by pszucs** [lainsce/khronos#17]
When a minute passes the 'seconds' part of the timer shows '60 secs' instead of showing the following minute and '0 secs', e.g. it shows `37mins, 60 secs` instead of `38 mins, 0 secs`.

Version: 1.0.0 (App Center)

![Screenshot from 2020-02-15 17-03-58](https://user-images.githubusercontent.com/2471046/74592140-3c561b00-5016-11ea-85c9-f0f5eaa4c425.png)

**Comment by lainsce** [comment]
This was fixed in a newer release bound to be in AppCenter soon.
