### ISSUE TITLE
Packaged in NixOS

### ISSUE THREAD

**Issue by worldofpeace** [lainsce/khronos#18]
### Description of issue
Hi, maintainer of elementary third party apps and Pantheon here from NixOS.
We're going to add an expression for NixOS into the nixpkgs repository https://github.com/NixOS/nixpkgs/pull/80555.

I was just wondering what https://github.com/lainsce/khronos/blob/master/nix/default.nix was for, or if you didn't want it in nixpkgs?

**Comment by lainsce** [comment]
It is for nixpkgs, sorry for not making a PR there.
Was waiting on a solution in Nix for pay-what-you-want model.

**Comment by vcunat** [comment]
We have `meta.homepage` field, so I can imagine having another specific field with a link (to [your patreon](https://www.patreon.com/lainsce) in this case, I assume).  I don't think that would help you noticeably, and I can't see what else could be done on this front.

**Comment by worldofpeace** [comment]
> Was waiting on a solution in Nix for pay-what-you-want model.

I'm not sure that's a thing that could be inside Nix, it sounds more like there's need for a front-end.

Like, perhaps we'd put Nix Packages into Flatpaks or Snaps.
PackageKit does have a Nix backend https://github.com/hughsie/PackageKit/tree/master/backends/nix, but I don't think it works anymore. There is an MVP for snap in nix https://github.com/NixOS/nixpkgs/blob/master/doc/builders/images/snap/example-firefox.nix, but TBH I don't care for snap, and I believe this community doesn't either :smile:

**Comment by lainsce** [comment]
Well, ideally Nix-Flatpak would be the way I want it to be so, can you do that?

**Comment by vcunat** [comment]
If I understand this correctly, Nix-generated Flatpack/Snap seems something you might put on your homepage, for example, but most likely not what would be normally installed by Nix users.

**Comment by lainsce** [comment]
I mean, a notice somewhere to my patreon perhaps, my apps in Arch's AUR have a notice to it.

**Comment by lainsce** [comment]
Closing this due to being out of my hands.
