### ISSUE TITLE
Tasks logged should have their start dates

### ISSUE THREAD

**Issue by MalteKiefer** [lainsce/khronos#2]
It would be nice to have in the right upper corner the date 

![screen](https://user-images.githubusercontent.com/59220985/74213439-7c757080-4c99-11ea-9658-4c7128c6d327.png)

**Comment by lainsce** [comment]
Which date would that be? Date the task was made?

Will add for the next release.

**Comment by MalteKiefer** [comment]
yes, when it starts.

2020/01/01

when it goes over days:

2020/01/01 - 2020/01/03

**Comment by lainsce** [comment]
I think I'll only have it mark the start date, no need for the span of dates.

**Comment by lainsce** [comment]
It'll be like this:
```
Task Name
0 mins, 18 secs
Started on: 2020-02-11
```

**Comment by MalteKiefer** [comment]
OK, maybe

2020-02-11 06:45

11.02.2020 07:52:27 Lains <notifications@github.com>:

**Comment by lainsce** [comment]
Even better.

**Comment by lainsce** [comment]
Fixed in repo.
