### ISSUE TITLE
Cannot add a task ("Add Log" button stays disabled)

### ISSUE THREAD

**Issue by asahnoln** [lainsce/khronos#21]
I cannot add a task. Whether I enter a name of a task or not, the "Add Log" button stays disabled. 

I have this problem both in 1.0.3 from AppCenter and in the latest master version built from the repository.

![Main window](https://user-images.githubusercontent.com/2792908/78058893-ce3d9b80-73aa-11ea-8046-bc3fbe5f5950.png)

**Comment by lainsce** [comment]
You need to start tracking the task's time first with the play button before adding it to the log and then reset the timer.
The log is the last stage of a task.

**Comment by asahnoln** [comment]
I see, sorry for creating an issue on this one. Is there a way to make it more intuitive? Maybe a little help note or something like that?

**Comment by lainsce** [comment]
I'll add a helpful tooltip to a (?) icon by the entry ;)
