### ISSUE TITLE
Idea: Integration with Toggl

### ISSUE THREAD

**Issue by agnishcc** [lainsce/khronos#23]
Hi, 

I really like the app design and I think it can really enhance if you had an integration with toggl. I can help you with that. Let me know if you are interested.

**Comment by lainsce** [comment]
If you mind the existing Pull Request and do a Pull Request for it on top of that Pull Request, I don't mind.
Just need to follow the elementary OS UI guidelines, and also the [solo Design System](https://lainsce.us/src/solo) guidelines.

**Comment by lainsce** [comment]
It's been a week, @agnishcc, with no replies...
