### ISSUE TITLE
Publish as flatpak on Flathub

### ISSUE THREAD

**Issue by lachmanfrantisek** [lainsce/khronos#30]
Hi,

Can you please submit Khronos on Flathub as flatpak?

(I've seen that [you've submitted](https://github.com/flathub/flathub/pull/2078) your other app to Flathub and would really appreciate this one being there as well.)

I hope I don't need to provide any reasoning, but I can if needed.

Thanks in advance!

**Comment by lainsce** [comment]
Khronos is still mid-porting to GNOME HIG and still has a few stuff that need to be rewritten for this goal. When I complete this, I'll do a flatpak submission.

**Comment by lachmanfrantisek** [comment]
OK, thanks for the info and quick response.

**Comment by lachmanfrantisek** [comment]
[That](https://github.com/flathub/flathub/pull/2083) was really quick. Thanks!
