### ISSUE TITLE
Bug: Time on logs labels is always the same

### ISSUE THREAD

**Issue by gavr123456789** [lainsce/khronos#31]
Version: 2.0.0 from flathub  
Looks like the time(11:11 in this case) is always taken from the program start, not when task was started.  
![изображение](https://user-images.githubusercontent.com/30507409/105985904-36cdd580-60ad-11eb-9913-97c702bcdf51.png)

**Comment by lainsce** [comment]
Will look into this.

**Comment by lainsce** [comment]
Fixed in repository.
