### ISSUE TITLE
Feature: Clicking on a past Log's name puts the name on the Log Entry for reuse

### ISSUE THREAD

**Issue by gavr123456789** [lainsce/khronos#33]
I think it will be convenient if you go back to the case that is not finished, click on the label of the log to insert the name automatically.

**Comment by lainsce** [comment]
Do you mean, to edit previously logged tasks names?

**Comment by gavr123456789** [comment]
No I mean clicking on a task in the log inserts its name in the input field for the next task.

**Comment by lainsce** [comment]
Even still, I think this is not doable since the task name is not a widget that can be "clicked" to be able to do something with it. :/

**Comment by lainsce** [comment]
But I'll look into it.

**Comment by lainsce** [comment]
Fixed in repository.
