### ISSUE TITLE
Feature: group multiple tasks

### ISSUE THREAD

**Issue by Samet-MohamedAmin** [lainsce/khronos#36]
It would be better if there is a possibility of grouping multiple tasks together with the sum of every single task log.

**Example**
- Before grouping

| task | time |
|---|---|
|read section 1| 00:10:00|
|wasting time|00:10:00|
|wasting time|00:10:00|
|read section1|00:10:00|
|read section1|00:10:00|

- After grouping

| task | time |
|---|---|
|read section 1| 00:20:00|
|wasting time|00:30:00|

**Comment by lainsce** [comment]
My idea was, that I'm still coding, is that the user would get the day's tasks and export them, then clear the list for the next day, dealing with the data elsewhere.

**Comment by lainsce** [comment]
Updated your issue to focus on one issue at a time, the issue of doing day/month/year is out of scope for the app.

**Comment by lainsce** [comment]
I've tried to do this, but it seems there's no way of doing this. Maybe it's better if you export the logs, and change the results elsewhere in another app.
