### ISSUE TITLE
Wrong start time in period

### ISSUE THREAD

**Issue by gavr123456789** [lainsce/khronos#39]
![изображение](https://user-images.githubusercontent.com/30507409/107282923-bc1d9680-6a6c-11eb-9e0b-b055a3949868.png)
After finish last task ("Видос 50 вопросов")
Start time of this task was set to 0:20, but actually it was finished in 0:20, not started.
So then period was wrong calculated from 0:20 to 1:50 (for sure you can see on screenshot that 0:20 is current time)

**Comment by lainsce** [comment]
When a task is started, it captures the time when you pressed Start Timer, so it shouldn't have done this.

**Comment by lainsce** [comment]
I don't know, but I didn't encounter this in my testing.

Closing.

**Comment by stove-panini** [comment]
![image](https://user-images.githubusercontent.com/6309939/128945777-b53a8d1c-21c7-4203-b88c-6a578fcf223b.png)

This happens to me as well. The end time is recorded as the start time and the duration of the task is added to that, causing the end time to be in the future!

**Comment by lainsce** [comment]
Hm... maybe it happens due to some Linux time problems? I'll look into this, maybe there's something happening with 24-hour time since both of you were in 24h time.

**Comment by stove-panini** [comment]
I could be off here as I'm not experienced w/ Vala, but this line seems to add the value of the timer to `dt`, which is populated when the "Add Log" button is pressed.
https://github.com/lainsce/khronos/blob/master/src/MainWindow.vala#L224

**Comment by lainsce** [comment]
You know, you might be onto something here. I'll look into moving `dt` creation to the "Start Timer" code and see what happens and will update this comment.

**Comment by stove-panini** [comment]
I'm happy to test when it's ready. Also, thanks for making this beautiful and super-useful time tracker! :)

**Comment by lainsce** [comment]
@stove-panini

Could you try it locally with GNOME Builder and pressing Run after cloning the Khronos repository to see if it worked? I think it's working correctly.

**Comment by stove-panini** [comment]
It's still a little strange. I've tested a couple runs and the logged times for both start and stop seem to be 10 seconds in the future. I've uploaded a video as an example.

https://user-images.githubusercontent.com/6309939/129263901-dac3b6b4-dfcb-487e-9798-68e4b83a1b61.mp4

**Comment by lainsce** [comment]
Well, it adds the timer's time directly to when the log was started, so a log of 11 seconds started at that time indeed would be at that time. It seems like the ticking for the timer is slightly faster than real time seconds so that's the new problem...

**Comment by stove-panini** [comment]
As I understand it, setting `dt` moved to the `timer()` function.
https://github.com/lainsce/khronos/blob/master/src/MainWindow.vala#L352

And this function is called by pressing the "Start Timer" button.
https://github.com/lainsce/khronos/blob/master/src/MainWindow.vala#L239

In the video clip, I started the timer at 16:03:40, which would set `dt` to that same value. Then the log should report the time range from `dt` to (`dt` + the timer value). But we can see that the start time is being displayed as 16:03:51, one second _before_ I hit "Add Log".

Again, I'm not well-versed in Vala, but I don't see where the Add Log button would be setting `dt`.

**Comment by lainsce** [comment]
"Add Log" doesn't set `dt` anymore as that's what was doing the original bug. But now I'll have to fix the disparity of `dt` when "Start Timer" is pushed.

**Comment by lainsce** [comment]
OK, now it should be good

**Comment by stove-panini** [comment]
Yes! It's working perfectly now. Thanks so much for helping out with this issue!
