### ISSUE TITLE
Personalized notification for ongoing tasks

### ISSUE THREAD

**Issue by MalteKiefer** [lainsce/khronos#4]
Nice would be a little notification after a user specified time, like one hour.

**Comment by lainsce** [comment]
Things like these will come in the next releases.

**Comment by lainsce** [comment]
Question: How would this happen? A notifier reminding you that a task is ongoing every X minutes, or like, "30 mins have passed doing Task X!"

**Comment by MalteKiefer** [comment]
The last one.

**Comment by lainsce** [comment]
Oh ok, so it's simpler. Could do it like this then:
- Notification pops for 30 min.
- Notification pops for 1 hr.
- Notification pops for 1 hr 30 min.
- Notification pops for 2 hr.
- Notification pops for 2 hr 30 min.

And then it ends, to promote changing tasks that are too long, logging them, and going into new ones.

**Comment by MalteKiefer** [comment]
I like it.

**Comment by lainsce** [comment]
Fixed.
