### ISSUE TITLE
Bad performance when resizing window

### ISSUE THREAD

**Issue by GustavoPeredo** [lainsce/khronos#48]
(I don't know what Screenkey is, sorry)
I'm having very bad performance when resizing the main window (the preferences one works fine), according to console output it's is trying to allocate GtkWidgets and having a hard time doing so:

![out](https://user-images.githubusercontent.com/30641461/110716520-1766b400-81e6-11eb-93c2-6471b3b9ec9b.gif)

**Comment by lainsce** [comment]
This is just a gtk4 bug. It's kinda difficult to babysit allocation when gtk4 is new and Vala gtk4 things need to update for the new allocation thing.

I can't do anything about it.

**Comment by GustavoPeredo** [comment]
Alright! Keep doing amazing work :)
