### ISSUE TITLE
Icons are hard to see on titlebar (dark mode)

### ISSUE THREAD

**Issue by GustavoPeredo** [lainsce/khronos#49]
I don't know if I'm alone here, but I'm having a hard time with the icons in the titlebar; their contrast is of 1.1:1, which I assume is unintentional (maybe gtk4 bug?)
![Captura de tela de 2021-03-10 21-19-50](https://user-images.githubusercontent.com/30641461/110716906-d7540100-81e6-11eb-8099-36f7767ec8ee.png)

**Comment by lainsce** [comment]
Khronos is not made to be in Dark Mode.

**Comment by GustavoPeredo** [comment]
But it has a dark mode option in the settings...

**Comment by GustavoPeredo** [comment]
![out](https://user-images.githubusercontent.com/30641461/110848726-2b192580-828d-11eb-8e43-3f504cf9dfca.gif)

**Comment by lainsce** [comment]
Wait, why did I say it didn't have a Dark Mode lol I must've been sleepy

OK, I'll see what that icon is doing.

**Comment by lainsce** [comment]
Fixed

**Comment by GustavoPeredo** [comment]
Hooray!
