### ISSUE TITLE
Export list to different formats

### ISSUE THREAD

**Issue by MalteKiefer** [lainsce/khronos#5]
It should be possible to export the times to different formats:

- [ ] CSV
- [ ] JSON
- [ ] PDF
- [ ] Simple text file

**Comment by lainsce** [comment]
Would you mind if I did a very good exporter to CSV and let other tools other than Khronos convert it to the other files?

**Comment by MalteKiefer** [comment]
Yes.
I create currently a invoice app. I will later crest a import for that file to generate a invoice.

11.02.2020 19:16:27 Lains <notifications@github.com>:

**Comment by lainsce** [comment]
So, you're ok on my idea above? I'll develop the exporting stuff for CSV then. :+1:

**Comment by MalteKiefer** [comment]
Yes, sorry for the delay.

**Comment by lainsce** [comment]
CSV exporter now in repo. Will release new things once the initial release happens.

**Comment by MalteKiefer** [comment]
ok thanks. hope it happens soon.
