### ISSUE TITLE
Be able to select and copy the title of a task

### ISSUE THREAD

**Issue by yannicka** [lainsce/khronos#50]
There is no way to copy the title of a task. It would be nice if it were possible to select the title, and also to add a button to copy the title with one click.

**Comment by lainsce** [comment]
If you click on an existing task in the Logs tab, the title is copied to the entry in Timer tab, to make a new task; dispensing the need to manually copy the title.

**Comment by yannicka** [comment]
Thank you for the information.

My use case: I want to be able to copy the title to paste it into my calendar.

**Comment by lainsce** [comment]
Yeah, then click on the task you want to have the title of, and copy it from the entry. :)
