### ISSUE TITLE
Feature Request: Add the ability to track tasks and calendar items directly from EDS (Evolution Data Server)

### ISSUE THREAD

**Issue by dbrandonjohnson** [lainsce/khronos#65]
It would be nice to populate the task tracking field with a task that from Gnome Todo and Calendar.

**Comment by lainsce** [comment]
The concept of Log on Khronos is different from a Calendar/Todo task. The Logs list supposed to be managed only from Khronos, via import (future ability) or export from Khronos. This is because it's not a Todo task, but a Log of something the user did.

**Comment by dbrandonjohnson** [comment]
I was no suggesting this should be come a todo application.  In the Gnome ecosystem that is being handled by Evolution or Gnome Todo.  My suggestion is purely around tracking time spent on tasks that are already stored in EDS.  It is more of a convenience to have a list of Todo and/or Calendar activities to select that a user would want to track in a log vs coping and pasting the task name that a user is tracking in Khronos.

**Comment by dbrandonjohnson** [comment]
Additional clarification on this @lainsce I was more so thinking of querying the data that is already in EDS (todo's and calendar entries) as activity suggestions, other than that interaction with EDS Khronos wouldn't need to in store anything else about the activity other than name of the task.

**Comment by lainsce** [comment]
The thing is, I would need to bring over all of EDS's dependencies and whatnot just to be able to do so, and then make the app have one huge dependency for one task :/
