### ISSUE TITLE
[Feature Request] Add Tags to a Task

### ISSUE THREAD

**Issue by dbrandonjohnson** [lainsce/khronos#66]
Most time tracking apps I've used in the past can add tags to the task you are tracking.  For example if I'm tracking a task for a client that is billable it would be nice to tag the task as billable along with the client name.

**Comment by lainsce** [comment]
@dbrandonjohnson 

Sorry for the wait; but couldn't you just write something like:

`[Billable] [Client Name] Task Name`

as the Log's name in the entry? It would do the same thing.

**Comment by dbrandonjohnson** [comment]
Since Khronos exporting to CSV, I will likely be importing it in an external database to help me handle billing.  It would be much easier if I could handle categories and/or tags in their respective fields out of the box vs manual manipulation of the CSV or write something so the data is easier to use.  I like the simplicity of the app but for complex workflows, this isn't going to work at least for me.

**Comment by lainsce** [comment]
Alright. I'll look into this after the rewrite of the backend. :)

**Comment by lainsce** [comment]
![shot2](https://user-images.githubusercontent.com/4886639/144547026-178801e1-ea77-47b4-a09a-001770d4b58c.png)

@dbrandonjohnson How's this? :D

**Comment by dbrandonjohnson** [comment]
It looks good.  I will take the time to build latest tomorrow and see how it functions and provide feedback.

**Comment by dbrandonjohnson** [comment]
I finally got a chance to test this.  I'll add it to my workflow and see how it works side by side with my current time tracker.  Couple of things @lainsce it would be nice to have a search function in the app and the ability to add tasks after they have occurred.  I can create additional issues for those RFEs if needed

**Comment by lainsce** [comment]
Actually I was about to add a searchbox in the logs view, but what do you mean by adding a task after they occur? What's the steps for that? :)
