### ISSUE TITLE
Untranslated subtitle

### ISSUE THREAD

**Issue by milotype** [lainsce/khronos#69]
Please check why Khronos’ text `Log the time it took to do tasks` doesn’t translate on the following pages (and I can’t figure out where that text comes from):
- https://world.pages.gitlab.gnome.org/apps-for-gnome/hr/
- https://world.pages.gitlab.gnome.org/apps-for-gnome/hr/app/io.github.lainsce.Khronos/

Also, on that second page further down the following text appears: `Not translated
This app is not available in your language.` (I’m using the Croatian locale) That’s strange, because Croatian is completely translated.

**Comment by lainsce** [comment]
These things aren't under my responsibility to know why they're broken, in this repository they are all OK.

**Comment by milotype** [comment]
@lainsce I’m sorry, but I don’t quite understand … The string `Log the time it took to do tasks` does not exist in the translation files. 
But I did find it on line 7 of the file https://github.com/lainsce/khronos/blob/master/data/io.github.lainsce.Khronos.appdata.xml.in

**Comment by lainsce** [comment]
oh! I see, I'll fix it, should be a small fix. Sorry for misunderstanding.
