### ISSUE TITLE
Crash on startup. glGetShaderiv yet again. 

### ISSUE THREAD

**Issue by faelana** [lainsce/khronos#76]
Hi, im submiting the same problem as on notejot:
https://github.com/lainsce/notejot/issues/308

![Screenshot from 2021-10-22 16-06-51](https://user-images.githubusercontent.com/46012160/138478632-127169d8-f5fd-497b-86b9-5918be4d3261.png)
![Screenshot from 2021-10-22 16-06-30](https://user-images.githubusercontent.com/46012160/138478404-ca1dba93-939b-41e5-981e-dc710a2c0675.png)

The same fix works.(see notejot issue)
Perhaps this can be a good hint.

**Comment by lainsce** [comment]
> > And again, this **isn't** on my side or my fault. Flatpak apps **shouldn't** expose the GPU and they should work fine.
> 
> I know they shouldnt but its a fact that it says it requieres gpu features and will crash without permission to it. All your apps i tried have this problem so i made this issue to show that further. Im not pointing the finger to whoose fault it is im merely trying to show  the problem (that other people as well confirmed). With another program having the same issue perhaps its to be looked.

The problem is that I can't simply expose the GPU to fix this for a subset of users.
