### ISSUE TITLE
Timer disappears on reboot, creates no log

### ISSUE THREAD

**Issue by kanterjoe** [lainsce/khronos#93]
Version 3.6.6
Installed via Software (Flathub) on Fedora Silverblue

I created a timer and started it. About an hour in to the timer, I rebooted my computer. I started Kronos back up because I kept working. The timer wasn't still running and it was not added to the logs. I can tell it wasn't added to the logs because this is my second timer and there is only one in the logs.

**Comment by lainsce** [comment]
Khronos' timer is session based, if you reboot, it'll reset to 00:00:00. Only what you add will be saved. I don't see how rebooting the system should leave Khronos running if the intention was to close all programs to reboot.

**Comment by adamijak** [comment]
It would be nice to save logs when you receive SIGTERM. This could partialy solve this issue.

**Comment by lainsce** [comment]
It's what is done. I don't control GTK's handling of closing windows, but stuff does save on window close.
