### ISSUE TITLE
Crashes on starup suddenly

### ISSUE THREAD

**Issue by aronkvh** [lainsce/khronos#99]
Hi, 
The app started crashing today with:
```
flatpak run io.github.lainsce.Khronos
(io.github.lainsce.Khronos:2): Gtk-WARNING **: 21:11:24.502: Locale not supported by C library.
        Using the fallback 'C' locale.
(io.github.lainsce.Khronos:2): Gtk-WARNING **: 21:11:24.520: cannot open display:
```
/home/aronkvh/.local/share/flatpak/app/io.github.lainsce.Khronos/x86_64/stable/active/files/bin/io.github.lainsce.Khronos: 
`error while loading shared libraries: libgtk-4.so.1: cannot open shared object file: No such file or directory`

system info:
Operating System: KDE neon 5.23
KDE Plasma Version: 5.23.4
KDE Frameworks Version: 5.89.0
Qt Version: 5.15.3
Kernel Version: 5.11.0-25-generic (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-3770 CPU @ 3.40GHz
Memory: 27,1 GiB of RAM
Graphics Processor: Mesa DRI Intel® HD Graphics 4000

**Comment by lainsce** [comment]
You need to install via flatpak a GNOME platform, for ex. 41, since your system is KDE based.

Not an issue. :)
